<a href="https://colab.research.google.com/github/Georgij38/DZ_11/blob/main/DZ_DS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
matrix = [[0 for _ in range(3)] for _ in range(3)]

for row in matrix:
    print(row)

[0, 0, 0]
[0, 0, 0]
[0, 0, 0]


In [ ]:
import random
matrix = [[random.randint(1, 10) for _ in range(5)] for _ in range(5)]

for row in matrix:
    print(row)

[7, 2, 3, 6, 3]
[2, 10, 9, 1, 2]
[1, 5, 1, 10, 10]
[4, 9, 6, 10, 1]
[9, 10, 4, 1, 7]


In [ ]:
import random
matrix = [[random.uniform(0, 1) for _ in range(4)] for _ in range(4)]

for row in matrix:
    print(row)

[0.8023061635667654, 0.8629109616437407, 0.9043698840339621, 0.8846588951715386]
[0.9672824061349058, 0.08026091686761672, 0.8874758564229964, 0.5883995633625637]
[0.22349378566477318, 0.5516636523649051, 0.982087615876658, 0.7752212057231961]
[0.8839224637904518, 0.9424127841341444, 0.8129136869416995, 0.9582788603096075]


In [ ]:
import numpy as np

array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

addarray = np.add(array1, array2)
subtractarray = np.subtract(array1, array2)
multiplyarray = np.multiply(array1, array2)

# Виводимо результати
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Результат додавання:", addarray)
print("Результат віднімання:", subtractarray)
print("Результат множення:", multiplyarray)

Масив 1: [ 5  9  4  7 10]
Масив 2: [7 1 9 9 3]
Результат додавання: [12 10 13 16 13]
Результат віднімання: [-2  8 -5 -2  7]
Результат множення: [35  9 36 63 30]


In [ ]:
import numpy as np

vector1 =  np.random.randint(1, 100, size=7)
vector2 =  np.random.randint(1, 100, size=7)

scalar_product = np.dot(vector1, vector2)

print("Скалярний добуток:", scalar_product)

Скалярний добуток: 22259


In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

result = np.dot(matrix1, matrix2)

print("Результат перемноження:")
print(result)

Результат перемноження:
[[ 30  92  69]
 [ 45 126 117]]


In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

inverse_matrix = np.linalg.inv(matrix)

print("Матриця:")
print(matrix)
print("\nОбернена матриця:")
print(inverse_matrix)

Матриця:
[[1 3 6]
 [5 1 7]
 [6 5 1]]

Обернена матриця:
[[-0.17801047  0.14136126  0.07853403]
 [ 0.19371728 -0.18324607  0.12041885]
 [ 0.09947644  0.06806283 -0.07329843]]


In [ ]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(4, 4))
transposed_matrix = matrix.T

print(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

[[0.9907812  0.38355074 0.0949305  0.51908186]
 [0.75243424 0.90500166 0.58070498 0.57441116]
 [0.58984928 0.23431457 0.45684509 0.76539829]
 [0.46414179 0.9276868  0.94447823 0.16925992]]

Транспонована матриця:
[[0.9907812  0.75243424 0.58984928 0.46414179]
 [0.38355074 0.90500166 0.23431457 0.9276868 ]
 [0.0949305  0.58070498 0.45684509 0.94447823]
 [0.51908186 0.57441116 0.76539829 0.16925992]]


In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=(4,))

result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження:")
print(result)

Матриця:
[[3 7 3 7]
 [1 9 8 5]
 [4 9 7 4]]

Вектор:
[2 2 7 2]

Результат перемноження:
[55 86 83]


In [ ]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(2, 3))

vector = np.random.uniform(0, 1, size=(3,))

result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("\nВектор:")
print(vector)
print("\nРезультат перемноження:")
print(result)

Матриця:
[[0.92344567 0.57065816 0.06477273]
 [0.17973721 0.94951032 0.55309206]]

Вектор:
[0.04282242 0.54206675 0.03150791]

Результат перемноження:
[0.35091985 0.53982153]


In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

elementwise_product = np.multiply(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Результат поелементного множення:")
print(elementwise_product)

In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nДобуток матриць:")
print(product)

Матриця 1:
[[8 3]
 [1 9]]

Матриця 2:
[[3 9]
 [8 1]]

Добуток матриць:
[[48 75]
 [75 18]]


In [ ]:
import numpy as np

matrix = np.random.randint(1, 101, size=(5, 5))

sum_of_elements = np.sum(matrix)

print("Сума елементів матриці:")
print(sum_of_elements)

Сума елементів матриці:
1442


In [ ]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

difference = np.subtract(matrix1, matrix2)

print(difference)

[[-4  3 -6  0]
 [ 3 -7 -4  4]
 [ 0 -1 -2  1]
 [ 1  2 -1 -3]]


In [34]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(3, 3))

row_sums = np.sum(matrix, axis=1)

print("Матриця:")
print(matrix)
print("Сума елементів кожного рядка:")
print(row_sums)

Матриця:
[[0.61551228 0.08773632 0.70485547]
 [0.57260487 0.15613223 0.2166885 ]
 [0.14637606 0.14033499 0.83677877]]

Сума елементів кожного рядка:
[1.40810407 0.9454256  1.12348982]


In [35]:
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 4))

squared_matrix = np.square(matrix)

print("Матриця:")
print(matrix)
print("\nМатриця з квадратами чисел:")
print(squared_matrix)

Матриця:
[[7 4 5 5]
 [3 7 4 4]
 [6 9 2 3]]

Матриця з квадратами чисел:
[[49 16 25 25]
 [ 9 49 16 16]
 [36 81  4  9]]


In [36]:
import numpy as np

vector = np.random.randint(1, 51, size=(4,))

square_roots = np.sqrt(vector)

print("Вектор:")
print(vector)
print("\nВектор з квадратними коренями чисел:")
print(square_roots)

Вектор:
[40 35 48 10]

Вектор з квадратними коренями чисел:
[6.32455532 5.91607978 6.92820323 3.16227766]
